### ISSUE TITLE
Agradecimentos

### ISSUE THREAD

**Issue by ricardokovalski** [carolcodes/front-end-do-zero#1]
Olá, boa tarde. Parabéns por criar este repositório com um passo-a-passo de como começar a codar em front-end. Sensacional a sua iniciativa e parabéns.

**Comment by rodolfopatane** [comment]
Também curti bastante, muitos tópicos que ainda quero ver, valeu pela publicidade do conteúdo, vai me ajudar bastante no próximo semestre, e acredito que a muita gente.

**Comment by carolsoaressantos** [comment]
Obrigada por isso <3
Eu vou atualizar e colocar mais coisas em breve.
